# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "German Flores"
tagline: ""
description: "Follow <a href=\"https://micro.blog/germanflores\">@germanflores on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/germanflores\">@germanflores on Micro.blog</a>."
baseurl: ""
url: "http://germanflores.com"
markdown: "kramdown"
username: "germanflores"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "German Flores"
name: "German Flores"
gravatar_hash: "366c20b75000715ee9ea80edabff9614"
avatar: "https://micro.blog/germanflores/avatar.jpg"
full_name: "German Flores"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: "3687"
gems: ["jekyll-paginate"]