# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: german flores
email:
description: German Flores Scrum Master, Team Development at Leapfrog Online. Chicago Illinois
logo: "/assets/images/logo.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://germanflores.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'german flores'
bio: I help organizations implement effective practices to manage work and grow people. I support teams at Leapfrog Online Direct Marketing. My opinions only.
author_image: "/assets/images/author.jpg"
twitter_username: germanflores
github_username:  germanflores


# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
  - jekyll-paginate

excerpt_separator: ""
