# # # # # # # #
#   K i k o   #
# # # # # # # #

# - markdown: kramdown

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

title: "German Flores"
tagline: ""
description: "Germán Flores helps teams implement effective practices to manage work and grow people using Agile principles and frameworks. I’m passionate about working with folks and helping them fulfill their potential."
credits: "credits"
baseurl: ""
url: "https://germanflores.github.io"
markdown: "kramdown"
username: "germanflores"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "German Flores"
name: "German Flores"
gravatar_hash: "366c20b75000715ee9ea80edabff9614"
avatar: "https://micro.blog/germanflores/avatar.jpg"
full_name: "German Flores"
bio: ""
twitter_username: "germanflores"
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "US/Indiana-Starke"
site_id: "3687"
plugins: ["jekyll-paginate"]
itunes_description: "I help teams implement effective practices to manage work and grow people using Agile principles and frameworks. I’m passionate about working with folks and helping them fulfill their potential."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "German Flores"
itunes_email: ""
podcast: false
